services:
  app:
    image: public.ecr.aws/a4j1j8l8/escore/openapi
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=password
      - API_KEY=${API_KEY:?API_KEY is required}
    ports:
      - 3306:3306
      
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql
    network_mode: "service:app" # app1의 네트워크를 공유
